# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  # Timeout for analysis
  timeout: 10m

  # Include tests
  tests: true

  # Go version to use for analysis
  go: "1.24.6"

formatters:
  enable:
    - gofmt      # Check gofmt formatting
    - goimports  # Check imports formatting and ordering

  settings:
    gofmt:
      # Simplify code (-s flag)
      simplify: true

    goimports:
      # Put local imports after 3rd party
      local-prefixes: github.com/bazelment/yoloswe

linters:
  # Disable all linters by default, enable specific ones
  default: none
  enable:
    # Bug detection
    - govet       # Official Go vet tool
    - staticcheck # Advanced static analysis
    - ineffassign # Detect ineffectual assignments

    # Style
    - misspell # Find misspelled English words
    - unused   # Find unused code

    # Best practices
    - revive   # Fast, configurable, extensible linter (replaces golint)
    - gocritic # Opinionated linter with many checks

  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF*"    # Disable quickfix suggestions
        - "-S1016"  # Type conversion suggestion
        - "-ST1000" # Package comment form
        - "-ST1022" # Const comment form

    govet:
      # Enable all analyzers except noisy ones
      enable-all: true
      disable:
        - shadow          # Common pattern in Go
        - unusedwrite     # Struct field initialization in tests

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: var-declaration
        - name: var-naming

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - whyNoLint       # Allow nolint without explanation for now
        - hugeParam       # Not critical, optimization suggestion
        - paramTypeCombine # Style preference
        - builtinShadow   # Common variable names like 'max', 'min'
        - importShadow    # Common variable names like 'context'
        - nestingReduce   # Style preference
        - octalLiteral       # Old octal style is still valid
        - preferStringWriter # Minor optimization
        - exitAfterDefer     # Common pattern in main()
        - ifElseChain        # Style preference
        - unnamedResult      # Style preference
        - typeDefFirst       # Style preference

  exclusions:
    # Exclude generated files
    generated: strict

    # Exclude some linters from running on tests
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gocritic

    # Common patterns that are safe to ignore
    paths:
      - third_party
      - vendor
