package main

import (
	"errors"
	"fmt"
	"io/fs"
	"os"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/bazelment/yoloswe/jiradozer"
)

// bootstrapArgs holds bootstrap-only flags.
type bootstrapArgs struct {
	output string
	force  bool
}

func newBootstrapCommand(args *bootstrapArgs) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "bootstrap",
		Short: "Generate a starter jiradozer.yaml",
		Long: `Write a jiradozer.yaml seeded with the canonical step prompts and
comment templates. Edit the prompts to taste; jiradozer no longer ships
built-in defaults, so the generated file is the source of truth for what
the agent says.`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			path := args.output
			if path == "" {
				path = "jiradozer.yaml"
			}
			if _, err := os.Stat(path); err == nil && !args.force {
				return fmt.Errorf("%s already exists (use --force to overwrite)", path)
			} else if err != nil && !errors.Is(err, fs.ErrNotExist) {
				return fmt.Errorf("stat %s: %w", path, err)
			}
			content, err := bootstrapYAML()
			if err != nil {
				return err
			}
			if err := os.WriteFile(path, content, 0o644); err != nil {
				return fmt.Errorf("write %s: %w", path, err)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "wrote %s\n", path)
			return nil
		},
	}
	cmd.SilenceUsage = true
	cmd.Flags().StringVarP(&args.output, "output", "o", "jiradozer.yaml", "Path to write the starter config")
	cmd.Flags().BoolVarP(&args.force, "force", "f", false, "Overwrite the output file if it already exists")
	return cmd
}

// bootstrapYAML returns the bytes of a starter jiradozer.yaml: the leading
// documentation block followed by the marshaled defaults plus the canonical
// prompts and comment templates from this file.
func bootstrapYAML() ([]byte, error) {
	cfg := starterConfig()
	body, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("marshal starter config: %w", err)
	}
	return []byte(bootstrapHeader + string(body)), nil
}

// starterConfig builds the *jiradozer.Config that bootstrap emits.
// Non-prompt fields come from jiradozer.DefaultConfig; the prompt and
// comment-template fields are filled in here so the YAML is the only place
// step prompts live going forward.
func starterConfig() *jiradozer.Config {
	cfg := jiradozer.DefaultConfig()
	cfg.Tracker = jiradozer.TrackerConfig{
		Kind:   "linear",
		APIKey: "$LINEAR_API_KEY",
	}
	cfg.Source = jiradozer.SourceConfig{
		Filters: map[string]string{
			"team":  "ENG",
			"state": "Todo",
		},
		BranchPrefix:  "jiradozer",
		MaxConcurrent: 3,
	}
	cfg.Plan.Prompt = bootstrapPlanPrompt
	cfg.Plan.CommentTemplate = bootstrapCompleteCommentTemplate

	cfg.Build.Prompt = bootstrapBuildPrompt
	cfg.Build.CommentTemplate = bootstrapCompleteCommentTemplate
	cfg.Build.RoundCommentTemplate = bootstrapRoundCommentTemplate

	cfg.Validate.Prompt = bootstrapValidatePrompt
	cfg.Validate.CommentTemplate = bootstrapCompleteCommentTemplate
	cfg.Validate.RoundCommentTemplate = bootstrapRoundCommentTemplate

	cfg.CreatePR.Prompt = bootstrapCreatePRPrompt
	cfg.CreatePR.CommentTemplate = bootstrapCompleteCommentTemplate

	cfg.Ship.Prompt = bootstrapShipPrompt
	cfg.Ship.CommentTemplate = bootstrapCompleteCommentTemplate
	cfg.Ship.RoundCommentTemplate = bootstrapRoundCommentTemplate

	return cfg
}

// bootstrapHeader is the documentation block prepended to the marshaled
// config. yaml.v3's encoder cannot emit head comments cleanly, so we stitch
// this in by hand.
const bootstrapHeader = `# jiradozer.yaml — generated by ` + "`jiradozer bootstrap`" + `. Edit prompts to taste.
#
# Template variables in step prompts and round prompts:
#   {{.Identifier}} {{.Title}} {{.Description}} {{.URL}} {{.Labels}}
#   {{.BaseBranch}} {{.Plan}} {{.BuildOutput}}
#
# Template variables in comment_template / round_comment_template:
#   {{.Step}} {{.Heading}} {{.Output}} {{.Round}} {{.TotalRounds}}

`

// The prompt strings below are the canonical defaults. They are byte-for-byte
// identical to the constants that previously lived in jiradozer/agent.go.
// jiradozer's runtime no longer reads them — they are emitted into the user's
// YAML and the YAML is the source of truth from then on.

const bootstrapPlanPrompt = `Issue: {{.Identifier}} — {{.Title}}
{{- if .Description}}

Description:
{{.Description}}
{{- end}}
{{- if .URL}}

URL: {{.URL}}
{{- end}}
{{- if .Labels}}
Labels: {{.Labels}}
{{- end}}

Create a detailed implementation plan for this issue. Include: files to modify, approach, testing strategy, and any risks.`

const bootstrapBuildPrompt = `Issue: {{.Identifier}} — {{.Title}}
{{- if .Description}}

Description:
{{.Description}}
{{- end}}
{{- if .Plan}}

Approved Plan:
{{.Plan}}

Implement the changes described in the approved plan above.
{{- else}}

No plan is available. Implement the changes based on the issue description above.
{{- end}}`

const bootstrapValidatePrompt = `Issue: {{.Identifier}} — {{.Title}}

Run the project's tests and linters to validate the changes. Fix any failures you find. Report what passed and what you fixed.`

const bootstrapCreatePRPrompt = `First, check for any uncommitted changes (staged or unstaged, including untracked files).
- If there are uncommitted changes: stage them, commit with a clear message referencing the work done, and push to the remote.
- If there are no uncommitted changes but unpushed commits: push to the remote.

Then, check if a pull request already exists for the current branch against {{.BaseBranch}}.
- If a PR exists: update its description to reflect the current state of the code. Report the PR URL.
- If no PR exists: create one against {{.BaseBranch}} with a clear title and description. Report the PR URL.`

const bootstrapShipPrompt = `Issue: {{.Identifier}} — {{.Title}}
{{- if .URL}}

Linear: {{.URL}}
{{- end}}

Check if a pull request already exists for the current branch against {{.BaseBranch}}.
- If a PR exists: update its description if needed and ensure it is ready for review. Report the PR URL.
- If no PR exists: create one using gh pr create with "{{.Identifier}}: {{.Title}}" as the title.`

// Comment templates: the previous hardcoded fmt.Sprintf strings translated
// into Go text/template syntax.
const bootstrapCompleteCommentTemplate = `## {{.Heading}} Complete

{{.Output}}`

const bootstrapRoundCommentTemplate = `## {{.Heading}} Round {{.Round}}/{{.TotalRounds}}

{{.Output}}`
