package main

import (
	"errors"
	"fmt"
	"io/fs"
	"os"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/bazelment/yoloswe/jiradozer"
	"github.com/bazelment/yoloswe/jiradozer/tracker"
)

// bootstrapArgs holds bootstrap-only flags.
type bootstrapArgs struct {
	output string
	force  bool
}

func newBootstrapCommand(args *bootstrapArgs) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "bootstrap",
		Short: "Generate a starter jiradozer.yaml",
		Long: `Write a jiradozer.yaml seeded with the canonical step prompts and
comment templates. Edit the prompts to taste; the generated file is the
source of truth for what the agent says.`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			path := args.output
			if path == "" {
				path = "jiradozer.yaml"
			}
			if _, err := os.Stat(path); err == nil && !args.force {
				return fmt.Errorf("%s already exists (use --force to overwrite)", path)
			} else if err != nil && !errors.Is(err, fs.ErrNotExist) {
				return fmt.Errorf("stat %s: %w", path, err)
			}
			content, err := bootstrapYAML()
			if err != nil {
				return err
			}
			if err := os.WriteFile(path, content, 0o644); err != nil {
				return fmt.Errorf("write %s: %w", path, err)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "wrote %s\n", path)
			return nil
		},
	}
	cmd.SilenceUsage = true
	cmd.Flags().StringVarP(&args.output, "output", "o", "jiradozer.yaml", "Path to write the starter config")
	cmd.Flags().BoolVarP(&args.force, "force", "f", false, "Overwrite the output file if it already exists")
	return cmd
}

// bootstrapYAML returns the bytes of a starter jiradozer.yaml: the leading
// documentation block followed by the marshaled defaults plus the canonical
// prompts and comment templates from this file.
func bootstrapYAML() ([]byte, error) {
	cfg := starterConfig()
	body, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("marshal starter config: %w", err)
	}
	return []byte(bootstrapHeader + string(body)), nil
}

// starterConfig builds the *jiradozer.Config that bootstrap emits.
// Non-prompt fields come from jiradozer.DefaultConfig; the prompt and
// comment-template fields are filled in here so the YAML is the only place
// step prompts live going forward.
func starterConfig() *jiradozer.Config {
	cfg := jiradozer.DefaultConfig()
	cfg.Tracker = jiradozer.TrackerConfig{
		Kind:   "linear",
		APIKey: "$LINEAR_API_KEY",
	}
	cfg.Source = jiradozer.SourceConfig{
		Filters: map[string]string{
			tracker.FilterTeam:  "ENG",
			tracker.FilterState: "Todo",
		},
		BranchPrefix:  "jiradozer",
		MaxConcurrent: 3,
	}
	cfg.Plan.Prompt = jiradozer.BootstrapPlanPrompt
	cfg.Plan.CommentTemplate = jiradozer.BootstrapCompleteCommentTemplate

	cfg.Build.Prompt = jiradozer.BootstrapBuildPrompt
	cfg.Build.CommentTemplate = jiradozer.BootstrapCompleteCommentTemplate
	cfg.Build.RoundCommentTemplate = jiradozer.BootstrapRoundCommentTemplate

	cfg.Validate.Prompt = jiradozer.BootstrapValidatePrompt
	cfg.Validate.CommentTemplate = jiradozer.BootstrapCompleteCommentTemplate
	cfg.Validate.RoundCommentTemplate = jiradozer.BootstrapRoundCommentTemplate

	cfg.CreatePR.Prompt = jiradozer.BootstrapCreatePRPrompt
	cfg.CreatePR.CommentTemplate = jiradozer.BootstrapCompleteCommentTemplate

	cfg.Ship.Prompt = jiradozer.BootstrapShipPrompt
	cfg.Ship.CommentTemplate = jiradozer.BootstrapCompleteCommentTemplate
	cfg.Ship.RoundCommentTemplate = jiradozer.BootstrapRoundCommentTemplate

	return cfg
}

// bootstrapHeader is the documentation block prepended to the marshaled
// config. yaml.v3's encoder cannot emit head comments cleanly, so we stitch
// this in by hand.
const bootstrapHeader = `# jiradozer.yaml — generated by ` + "`jiradozer bootstrap`" + `. Edit prompts to taste.
#
# Template variables in step prompts and round prompts:
#   {{.Identifier}} {{.Title}} {{.Description}} {{.URL}} {{.Labels}}
#   {{.BaseBranch}} {{.Plan}} {{.BuildOutput}}
#
# Template variables in comment_template / round_comment_template:
#   {{.Step}} {{.Heading}} {{.Output}} {{.Round}} {{.TotalRounds}}

`
